#define __COMMA ,__NL__

#define TASKS_JSON(CONFIGURATIONS) \
{ __NL__ \
__TAB__	"version": "2.0.0", __NL__ \
__TAB__	"tasks": [ __NL__ \
		CONFIGURATIONS __NL__ \
__TAB__	] __NL__ \
} __NL__

#define TASK_CONFIG(NAME) \
__TAB__ __TAB__		{__NL__ \
__TAB__ __TAB__ __TAB__   "type": "shell",__NL__ \
__TAB__ __TAB__ __TAB__   "label": __QUOTE__build NAME##__QUOTE__,__NL__ \
__TAB__ __TAB__ __TAB__   "command": "make",__NL__ \
__TAB__ __TAB__ __TAB__   "args": [],__NL__ \
__TAB__ __TAB__ __TAB__   "options": {__NL__ \
__TAB__ __TAB__ __TAB__ __TAB__      "cwd": "${cwd}"__NL__ \
__TAB__ __TAB__ __TAB__   },__NL__ \
__TAB__ __TAB__ __TAB__   "group": {__NL__ \
__TAB__ __TAB__ __TAB__ __TAB__      "kind": "build",__NL__ \
__TAB__ __TAB__ __TAB__ __TAB__      "isDefault": true__NL__ \
__TAB__ __TAB__ __TAB__   },__NL__ \
__TAB__ __TAB__ __TAB__   "detail": "generated by build chain"__NL__ \
__TAB__ __TAB__        }
